# values.yaml
replicaCount: 1 # Start with 1 replica for initial testing, but be prepared to change this based on your observation!
image:
  repository: ghcr.io/cloudraftio/metrics-app
  pullPolicy: IfNotPresent
  tag: "1.1" # Use the specified tag

service:
  type: ClusterIP # Or LoadBalancer if your KIND setup supports it, but ClusterIP is standard for Ingress
  port: 80 # Service port
  targetPort: 8080 # Container port

# Other values like serviceAccount, resources, etc., can be left as default or adjusted
secretPassword: "MYPASSWORD"
