# metrics-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "metrics-app.fullname" . }}-ingress
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
  # Add annotations here if needed for your specific ingress controller
  # e.g., for Nginx ingress:
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  #   nginx.ingress.kubernetes.io/use-regex: "true" # Needed if using regex paths
spec:
  ingressClassName: nginx # MUST match the name of your installed IngressClass
  rules:
  - host: # Leave empty for localhost access via IP or port-forwarding
    http:
      paths:
      - path: /counter # The path you want to expose
        pathType: Prefix # Or ImplementationSpecific
        backend:
          service:
            name: {{ include "metrics-app.fullname" . }} # Name of the service created by your chart
            port:
              number: {{ .Values.service.port }} # The service port (e.g., 80)
