# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics-app.fullname" . }}-secret # Matches the name in deployment.yaml
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Secrets data must be base64 encoded
  PASSWORD: {{ .Values.secretPassword | b64enc | quote }}
