# metrics-app/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics-app.fullname" . }}-secret
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ .Values.secretPassword | b64enc | quote }}
